name: FTP Deploy

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  ftp-deploy:
    # runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: myportfolio/  # Local directory to deploy
          server-dir: /htdocs  # Directory on the server